name: uts
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.1
  bmi_calculator: ^1.0.0
  flutter_hooks: ^0.18.0
  http: ^0.13.3
  charts_flutter: ^0.12.0
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
